Issue 19 User rename, User 인터페이스 추가
f-lab-edu/twitch-clone pull request #20
Opened 2022-04-05 12:06 UTC by DoLiLu

2022-04-05 12:12 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateAdminUserUseCase.kt
rename commit의 경우 rename만 한 커밋이라 file changed가 룰보다 많지만 무시하는 형태로 진행 하였습니다.
pull request를 rename만 하는게 맞는가 고민 하다가 첫 커밋은 리뷰 없이 넘어간다고 가정하고
리뷰를 해야 할 다음 커밋만 생성하여 pull request진행 하였는데, 이와 같은 케이스도 pull request 따로 진행 하여야 할까요?

2022-04-05 12:12 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/model/Editable.kt
> +}
수정 관련 방법을 고민하다 sandbox를 참조 하였는데, 다른 좋은 방법이 있다면 수정 하겠습니다.

2022-04-05 12:12 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserPasswordService.kt
> +                userRepository.save(it)
관련하여 고민했던 부분이
1. 불변객체 유지 vs 객체 생성 시 상태 값 고정
	- 객체 생성 시 상태 값을 고정하는 방향으로 의견이 모아진 것 같아서 불변객체 유지를 포기하였습니다.
	- 둘 다 해보려고 고민 하였으나 최대한 불변에 가깝게 하는 방법이 값 변경 시 새로운 객체를 만들며 변경 된
	   값으로 생성 후 상태 값을 추가로 set 해줘야 하는 이슈가 있어서 일단 방향을 바꿨습니다.
            -> 불변 객체만 생성 시 상태 값이 초기화 되는 이슈가 있습니다.

2. 값 변경 인터페이스를 별도로 생성 vs 인터페이스에서 변경이 필요한 값만 var로 생성
	- 처음에 인터페이스에서 변경이 필요한 값만 var로 생성 후 코딩 진행 하였으나, 인터페이스에 공통으로 사용 
	   하여야 하는 fun을 선언할 경우 유저 상태 값 변경을 setter로 접근 할 수 없도록 하는 방법이 없어  변경
           인터페이스를 별도로 생성 하여 진행 하였습니다.

2022-04-05 12:12 UTC, DoLiLu commented on module-user/src/test/kotlin/com/example/user/util/MockUserRepository.kt
> +        return normalUser
repository 저장 및 반환 티입 관련해서

User Interface를 구현하는 구현체가 NormalUser, StreamerUser, AdminUser 3종류가 될 예정 인데
각각의 repository에 저장, 가져올 때 User 형태로 저장, 가져오는것이 맞는지 각 구현체 타입으로 저장, 가져오는 것이 맞는지 좀 헷갈립니다.

User 타입으로 진행 시 다른 구현체도 저장이 되는 상황이 생겨서 정합성 이슈가 발생 할 것 같고, 각 구현체로 진행 시 인터페이스의 장점을 제대로 활용하는 것이 맞나? 라는 생각이 들었습니다. 관련하여 의견 부탁드립니다.

2022-04-05 12:13 UTC, DoLiLu commented
이번 PR과 관계 없이 UseCase에 대하여 정리를 좀 해야 할 것 같습니다.
1. UseCase당 각 기능 1개로 하고 helper or manager 를 따로 만든 뒤 Service에서 사용 한다.
2. UseCase당 각 기능 1개로 하고 Service에서 여러 UseCase를 구현한다.
3. 비슷한 기능은 하나의 UseCase에서 선언한다.

이 정도가 될 것 같은데. 앞으로 어떻게 진행할지 정해야 할 것 같습니다. 정해지면 그 룰에 맞춰서 기존 로직 변경 하면 될 것 같습니다.

2022-04-05 12:50 UTC, Hyune-c commented
> 이번 PR과 관계 없이 UseCase에 대하여 정리를 좀 해야 할 것 같습니다.

- UseCase당 각 기능 1개로 하고 Service에서 여러 UseCase를 구현한다.

전 2번이 좋다고 생각합니다.

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +    val status: UserStatus
변수 사이에는 개행이 없는 것이 좋다고 생각합니다.
예외적으로 변수가 많아서 의미 있는 구분을 해야되는 경우에는 예외로 합니다.

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +        override var nickname: String
닉네임은 지금은 아니지만 차후 수정될 기능이 있을 것이기에 미리 넣은거죠?

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/test/kotlin/com/example/user/application/service/CreateNormalUserServiceTest.kt
>  @DisplayName("[회원] 생성")
```suggestion
@DisplayName("[일반 회원] 생성")
```

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/test/kotlin/com/example/user/application/service/FindNormalUserServiceTest.kt
>  @DisplayName("[유저] 조회")
```suggestion
@DisplayName("[일반 회원] 조회")
```

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/test/kotlin/com/example/user/application/service/UpdateNormalUserServiceTest.kt
>  @DisplayName("[회원] 정보 수정")
```suggestion
@DisplayName("[일반 회원] 정보 수정")
```

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/test/kotlin/com/example/user/domain/model/NormalUserTest.kt
>  @DisplayName("[회원] 일반")
```suggestion
@DisplayName("[일반 회원]")
```

2022-04-05 13:12 UTC, Hyune-c commented on module-user/src/test/kotlin/com/example/user/util/MockUserRepository.kt
> +        return normalUser
- 먼저 저는 추상체인 User가 들어가는게 맞다고 생각합니다.
- 하지만 정수님이 고민하는 것도 이해가 됩니다.
    - 추상체인 User를 구현체인 NormalUser, StreamerUser, AdminUser로 변환하는 과정을 어떻게 판단할 것인가?
    - UserType을 별도로 두어 어떤 구현체인지 판단해야될까요? 별로 이쁘지가 않네요. @FrancescoJo

2022-04-06 00:34 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/model/Editable.kt
> +}
이거 굳이 따라하실 필요는 없습니다

2022-04-06 00:35 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserPasswordService.kt
> +                userRepository.save(it)
제가 제시해 드린 스타일은 외부에 보이는 형태가 immutable 일 뿐 내부적으로는 mutable 입니다.

이것도 코드리뷰 등으로 보완할 수 있는 요소기도 하기 때문에 효율이 너무 떨어진다 싶으면 굳이 따라하지 않으셔도 괜찮습니다.

2022-04-06 00:36 UTC, FrancescoJo commented on module-user/src/test/kotlin/com/example/user/util/MockUserRepository.kt
> +        return normalUser
Type 을 둬서 구현체인지 판단하는건 java 스러운 방식이고요, `sealed interface`, `sealed class` 로 하위타입을 제한두는 방식이 좋을 것 같아요.

그리고 1개의 Aggregate 에는 1개의 Repository 가 오도록 구현하시는 편이 좋습니다.

2022-04-06 00:37 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserService.kt
>              userRepository.findById(id).let {
저는 `let` 을 주로 null-safe explicit receiver 가 필요할 때 활용하는 편입니다.

2022-04-06 00:37 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +    val status: UserStatus
뭐 이거는 스타일 정하기 나름이니까요. 참고로 저는 detekt 에서 뭐라 안하면 신경 안 쓰는 주의.

2022-04-06 00:38 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +        override var nickname: String
제 생각엔 지금 필요없다면 굳이 안해도 될 것 같아요.

2022-04-06 00:42 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +        override var nickname: String
내정보 변경 기능에 닉네임 변경 기능이 존재합니다.

2022-04-06 00:42 UTC, FrancescoJo requested changes
`NormalUser` 관련 repository 수정해주세요

- https://spring.io/blog/2018/09/24/spring-data-jdbc-references-and-aggregates
- https://www.popit.kr/%EC%97%90%EA%B7%B8%EB%A6%AC%EA%B2%8C%EC%9E%87-%ED%95%98%EB%82%98%EC%97%90-%EB%A6%AC%ED%8C%8C%EC%A7%80%ED%86%A0%EB%A6%AC-%ED%95%98%EB%82%98/

복습합시다

2022-04-06 00:43 UTC, DoLiLu commented
> > 이번 PR과 관계 없이 UseCase에 대하여 정리를 좀 해야 할 것 같습니다.
> 
> * UseCase당 각 기능 1개로 하고 Service에서 여러 UseCase를 구현한다.
> 
> 전 2번이 좋다고 생각합니다.

이것도 별도 ISSUE로 빼서 진행 하면 될 것 같습니다.

2022-04-06 00:59 UTC, DoLiLu commented on module-user/src/test/kotlin/com/example/user/util/MockUserRepository.kt
> +        return normalUser
처음에 얘기 하고 싶었던 부분은 `UserRepository`에 `save` 기능의 `return` 값이나 매개변수가 `User`가 되면 
`StreamerUser`, `AdminUser`도 `UserRespotiroy`를 통하여 save할 수 있는 이슈가 있어서 얘기 했던 부분인데 전달을 제가 잘 못한것 같습니다.

멘토님 말씀대로`NormalUserRepository` 로 진행하면 없어질 이슈라 `NormalUserRepository`로 진행 하도록 하겠습니다.

2022-04-06 01:08 UTC, DoLiLu commented on module-user/src/test/kotlin/com/example/user/domain/model/NormalUserTest.kt
>  @DisplayName("[회원] 일반")
관련 용어들 정리 하면서 회원 이라는 명명 규칙 전부 유저로 변경 할까 합니다.
User라는 클래스 하나를 유저, 회원으로 섞어 부르는것 같아서 유저로 통일 하면서 명명규칙 사전을 하나 만들면 괜찮을 것 같습니다.

2022-04-06 04:37 UTC, FrancescoJo commented on module-user/src/test/kotlin/com/example/user/domain/model/NormalUserTest.kt
>  @DisplayName("[회원] 일반")
> 관련 용어들 정리 하면서 회원 이라는 명명 규칙 전부 유저로 변경 할까 합니다.
> User라는 클래스 하나를 유저, 회원으로 섞어 부르는것 같아서 유저로 통일 하면서 명명규칙 사전을 하나 만들면 괜찮을 것 같습니다.

좋습니다. 이게 DDD 에서 말하는 'Ubiquitous Language' 가 되겠네요. UL 통일은 중요하죠.

2022-04-06 23:51 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserPasswordService.kt
>      // 추후 설정 파일이나 외부 주입으로 변경
왠만하면 지금 하시는 편이 좋을 것 같아요. 그렇게 오래 안 걸릴거에요.

2022-04-06 23:53 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserService.kt
>       * - 항상 새로운 객체를 만듭니다.
코멘트와 실제 동작이 다르네요

2022-04-06 23:56 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/User.kt
> +    interface Editor : User {
이런거 굳이 안 따라하셔도 됩니다. model 을 immutable 로 하셔도 괜찮아요.
이런 구현으로 인한 불편함도 상당하기 때문입니다. 그리고 User 의 필드가 val 이라 하더라도 edit 를 어차피 노출하기 때문에 pure immutable 이라고 부르기에도 무리가 있고요.

저희회사에서 이렇게 구현한 이유는 수정 의도를 명확하게 비즈니스 로직에서 밝히라는 의도가 있어서였습니다.

2022-04-07 00:31 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserPasswordService.kt
>      // 추후 설정 파일이나 외부 주입으로 변경
UseCase당 기능 하나를 말씀하시는 걸까요? 그건 같이 진행 했습니다.

2022-04-07 09:58 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateUserPasswordService.kt
>      // 추후 설정 파일이나 외부 주입으로 변경
initPassword를 말씀하시는 것 같아요.

2022-04-07 11:23 UTC, DoLiLu commented
모든 파일, function 등 User로 되어 있던 것들을 전부 다 `NormalUser`로 변경 하였습니다.
변경하다가 궁금한점이 하나 생겼는데 예를 들어 비밀번호 변경 로직 `UpdateNormalUserPasswordUseCase` 의 경우
`NormalUser`, `StreamerUse`r, `AdminUser` 모두 패스워드 변경이 가능 하여야 하는데
기능 자체는 `User.Editor Interface`의 `updatePassword`를 공통으로 사용하게 됩니다.

기존에 항상 적용하던 DB 관점에서 password는 일반 유저 table에만 존재할 것이고 일반 유저에서만 변경 하면 되어 문제가 없었던 것 같은데 객체와 인터페이스 관점에서는 `스트리머 유저도 패스워드 변경을 할 수 있어야 한다.`가 맞는것 같아 고민이 됩니다.

스트리머 유저의 패스워드 변경 시 `UpdateStreamerUserPasswordUseCase`를 따로 만들어야 하는걸까요?

관련하여 Aggregate를 나누면서 일반 유저와 스트리머 유저를 분리 하였는데,
A라는 유저가 스트리머 회원이 되고나서 유저 패스워드를 변경한다면 A의 스트리머 리포지터리는 데이터를
어떻게 갖고 있어야 하는걸까요? 동기화 로직을 따로 만들어야 하는걸까요?

관련 의견 부탁드립니다.

2022-04-07 23:38 UTC, FrancescoJo approved these changes
나머지는 infra 구현때 또 필요하면 수정해 보시죠

2022-04-08 00:34 UTC, merged