Issue 19 User Interface 확장하여 StreamerUser 생성
f-lab-edu/twitch-clone pull request #21
Opened 2022-04-06 11:32 UTC by DoLiLu

2022-04-06 11:41 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +    var streamerStatusVar: StreamerUserStatus = StreamerUserStatus.PENDING
streamerStatus를 setter를 통하여 수정 할 수 없도록 하기 위하여 적용한 로직입니다.

만약 앞으로 이 형태로 변경을 관리 하려면 상태 관리 or 값 관리용 변수 네이밍이 필요 할 것 같습니다.
_streamerStatus 형태로 하려 하였으나 detekt에 걸려서 임의 접두어로 Var를 붙였습니다. 관련 네이밍을 어떻게 하면 좋을까요?

2022-04-06 11:41 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +
streamerStatus 변경을 매개변수를 통하여 하지 않고 분리하였는데, 매개변수를 통하여 수정하도록 하면
setter와 큰 차이가 없어 보여서 상태 변경을 각각 분리하였습니다.

너무 과하게 분리한것 같기도 하여 관련 내용 의견 부탁드립니다.

2022-04-06 11:41 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +class StreamerUser(
`class name` 관련해서 `Streamer`, `StreamerUser` 중에 결정하여야 할 것 같습니다.
`NormalUser`의 경우` Normal`에 유저라는 뜻이 없어서 필요한 것 같은데 
`Streamer`, `Admin` 의 경우 뒤에 `User`를 붙이면 유저라는 뜻이 반복 되는 느낌이라 빼는것도 괜찮아 보입니다.

전체의 통일성을 위하여 `User`를 다 붙일 것인지 의사결정이 필요합니다.
명명 규칙도 스트리머 or 스트리머 회원, 어드민 or 어드민 회원 중에 선택해야 할 것 같습니다.

2022-04-06 11:55 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +
- 상태가 늘어나면 메서드가 더 생겨야되고, 현재 상태에 관계 없이 강제로 변경시킬 수 있군요.
    - enum 에서 다음 상태를 관리하는 방법이 있을 것 같긴 합니다.
    - 사실 실무에서는 이렇게 많이 하긴 했는데.. 더 좋은 방법이 있을까요? @FrancescoJo 
- 이 메서드들은 이미 StreamerUser 객체가 사용하는 것입니다. 따라서 Streamer라는 접미사를 계속 붙여주지 않아도 된다고 생각합니다.

2022-04-06 11:56 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +    var streamerStatusVar: StreamerUserStatus = StreamerUserStatus.PENDING
이런 식의 코딩을 처음해봐서.. 리뷰를 부탁드립니다. @FrancescoJo

2022-04-06 11:57 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +class StreamerUser(
- 저는 일관성을 위해 User가 접미사로 붙는 것이 좋다고 생각합니다.
- 이전 pr 에서 유비쿼터스 언어로 `회원`이 아닌 `유저`를 택하기로 하였음으로
    - 스트리머 유저, 어드민 유저로 통칭하는 것이 좋다고 생각합니다.

2022-04-06 12:05 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateStreamerUserUseCase.kt
> +)
1. StreamerUser는 NormalUser가 존재해야만 생성할 수 있습니다. 따라서 NormalUser의 id만 받도록하는 것이 좋을 것 같습니다.
    - 이제보니 이전의 NormalUser를 통째로 받는 것도 좋은 형태는 아니었던 것 같습니다.
2. 현재의 구성이라면 이 요청이 들어오는 사이에 nickname이 변경되어 버리면 잘못된 정보가 덮어써질 수 있습니다.

2022-04-06 12:13 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +class StreamerUser(
회원이라고 잘 못 써놨군요.. 
접미사로 User가 붙는다면 말씀하신대로 명칭도 뒤에 유저를 붙여야 할 것 같습니다.

2022-04-06 12:17 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +class StreamerUser(
다시 한번 생각해보니 실무라면 `스트리머 유저, 어드민 유저로 해주세요.` 라고 말해도 분명히 안지켜질 확률이 훨씬 높겠군요.. 
아래처럼 하는 것이 현실적일 것 같습니다.

- 코드에는 접미사를 유지한다.
    - NormalUser, AdminUser, StreamerUser
- 한글을 사용할 때는 유저라는 접미사를 빼도 된다.
    - 일반유저, 어드민, 스트리머

2022-04-06 22:20 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateStreamerUserUseCase.kt
> +)
말씀하신대로 Command를 잘 못 수정한것 같아 변경하는것이 맞는것 같은데,
`NormalUser`를 받아야 값 변경에 대한 리스크를 최소화 할 수 있는 것이 아닐까요?

`id`만 받을 경우 email, password, nickname 모두 `NormalUser`와 다른 값이 들어와도 정상적으로 생성 될 것 같습니다.
`nickname`뿐 아니라 `password`도 마찬가지 일것 같은데, 동기화 관련 이슈는 좀 더 고민을 해봐야 할 것 같습니다.

2022-04-06 23:58 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateStreamerUserUseCase.kt
> +)
```
CreateStreamerUserCommand.from(user: NormalUser).copy(
  // 진짜 변경할 필드들...
)
```

뭐 이런 방식으로 구현하실 수도 있어 보이네요

2022-04-06 23:59 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/port/in/SuspendStreamerUserUseCase.kt
> +    fun suspendStreamer(id: UUID)
이런 동작도 왠만하면 반환값이 있는 편이 후속조치 하기 좀 더 좋을 것 같아요

2022-04-07 00:00 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/port/in/UpdateStreamerUserUseCase.kt
>      fun updateStreamerNickname(id: UUID, updateNickname: String)
변경된 이용자의 상태를 반환하게 한다면 좀 더 좋아보이네요. method chaining 이 가능할 것 같아서요.

2022-04-07 00:02 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/CreateStreamerUserService.kt
> +        val streamerUser = StreamerUser(
뭐 이렇게 코딩하셔도 상관없기는 한데, 저라면 `createStreamerUserCommand` literal 반복을 이렇게 해결할 것 같습니다.

```
val streamerUser = createStreamerUserCommand.let {
  StreamerUser(
    id = createStreamerUserCommand.id,
    email = createStreamerUserCommand.email,
    password = createStreamerUserCommand.password,
    nickname = createStreamerUserCommand.nickname,
    createStreamerUserCommand.streamerUserNickname
  )
}
```

2022-04-07 00:05 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateStreamerUserService.kt
>      override fun approveStreamerUser(streamerUsers: List<StreamerUser>) {
저라면 Rich domain model 로 이런 기능을 이렇게 구현할 것 같아요.

```
class StreamerUser {
  private var _status: StreamerUserStatus = StreamerUserStatus.UNDEFINED

  val status: StreamerUserStatus
    get() = _status

  fun approve(): StreamerUser {
    this._status = StreamerUserStatus.REGISTERED
    return this
  }
}
```

다른 기능들도 비슷하게요. 지금은 단순히 assign 만 하니까 이게 무슨 의미가 있냐 싶겠지만 approve 이후에 추가로 해야 할 일들이 생긴다면 그때부터는 이런 구현이 의미를 가질 것 같아요.

2022-04-07 00:06 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateStreamerUserService.kt
>      override fun approveStreamerUser(streamerUsers: List<StreamerUser>) {
이렇게 구현하면 User Service 가 할 일이 `저장` 하나로 대폭 줄고, `approve` 같은 메소드 호출의 책임을 Use Case 들로 분산할 수 있을 것 같습니다.

2022-04-07 00:07 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +class StreamerUser(
UL 정하실때는 여기 정한 단어로만 말 해도 말이 통하도록 하셔야 합니다. 그래서 이렇게 소통하실거면 `스트리머 유저` 라고 하시는 편이 좀 더 좋아보여요

2022-04-07 00:09 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +    var streamerStatusVar: StreamerUserStatus = StreamerUserStatus.PENDING
private backing field 를 쓰시면 괜찮아 보여요.

```
    override val status: UserStatus
      get() = _status

    private var _status: StreamerUserStatus = StreamerUserStatus.PENDING
```

2022-04-07 00:12 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +
위쪽에도 코멘트 했지만 저는 이런 구현이 오히려 좋다고 봅니다. 지금 하고 계신게 Richer domain model 을 만드는 거에요.
가령 이용자를 suspend 처리할 때, 채널을 모두 닫아라 같은 추가기능이 생긴다던가... 할 수도 있겠죠.

굳이 이런 식으로 setter 로 구현할 수도 있긴 한데,

```
override var status: UserStatus
  get() = _status
  set(value) {
    _status = value
    when(value) {
      StreamerUserStatus.REGISTERED -> this.registeredStreamer()
      // ...
    }
  }

private var _status: StreamerUserStatus = StreamerUserStatus.PENDING

private fun registeredStreamer() { ... }
```

값 자체에 비즈니스 로직을 바로 연결하는건... 이 값을 정말 잘 정의해서 영원히 안 바꿔도 된다 같은 상황이 아니라면 위험해 보이네요. 저라면 오히려 이렇게 구현하신것 처럼 할 것 같습니다.

2022-04-07 00:13 UTC, FrancescoJo requested changes
소소한 변경들 말고는 전반적으로 큰 문제 없어 보입니다.

2022-04-07 00:36 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateStreamerUserService.kt
>      override fun approveStreamerUser(streamerUsers: List<StreamerUser>) {
아 UserService에서 각 UseCase 구현하는게 아니고
각 UseCase와 그걸 구현하는 UseCaseImpl을 다 따로 만들자고 하시는게 맞을까요?

2022-04-07 00:38 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/domain/model/StreamerUser.kt
> +    var streamerStatusVar: StreamerUserStatus = StreamerUserStatus.PENDING
private가 빠져있긴 한데 backing field 사용하는 형태로 구성되어 있습니다.
네이밍이 _로 시작하는 형태가 detekt에 걸려서 뒤에 Var를 붙여 놓은 상태입니다.
private 추가하는 형태로 진행하면 문제 없을까요?

2022-04-07 00:45 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/UpdateStreamerUserUseCase.kt
>      fun updateStreamerNickname(id: UUID, updateNickname: String)
CQS를 지키려고 하다보니 나온 구조인데, 변경된 유저 정보가 아닌 유저의 상태값만 반환 하자고 하시는 걸까요?

2022-04-07 10:04 UTC, Hyune-c commented on module-user/src/main/kotlin/com/example/user/application/port/in/SuspendStreamerUserUseCase.kt
> +    fun suspendStreamer(id: UUID)
이런 상태 변경에 대해서는 조금 다른 생각을 가지고 있는데요.
반환 값을 가지고 한다기보다는 

- 성공하면 그냥 지나감
- 실패하면 저 메서드 내부 로직에서 exception이 발생함

try-catch가 필요할수도 있겠지만 추상화라는 관점에서 이 형식을 선호하는데 어떻게 생각하시나요?

2022-04-07 10:48 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateStreamerUserUseCase.kt
> +)
말씀하신 방법도 괜찮아 보이는데 일단은 `NormalUser` 넘기는 형태로 진행 하였습니다.
`CreateStreamerUserService`에서 `normalUserRepository`를 호출해야 하는데
 서로 다른 `Aggregate`의 `Repository`를 갖고 있는게 맞는건가에 대한 판단이 서지 않아 관련 의견 부탁드립니다.
@FrancescoJo

2022-04-07 23:55 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/port/in/SuspendStreamerUserUseCase.kt
> +    fun suspendStreamer(id: UUID)
저는 추상화보다는 그냥 흐름제어 관점에서 말씀 드렸습니다.

저장을 못하면 무조건 예외로 처리할지의 문제 같아 보이네요. 저는 그렇지는 않다 생각하거든요

`File.delete()` 메소드가 exception 도 던지고, boolean 도 반환하는 이유가 뭘까요?

2022-04-08 00:40 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/SuspendStreamerUserUseCase.kt
> +    fun suspendStreamer(id: UUID)
exception 관련은 멘토님 말씀대로 흐름제어쪽 관점인것 같고 반환값의 경우 이것도 trade-off라고 생각합니다. 
제 생각은 CQS를 지켜 수정만 하느냐, 수정 후 후속 조치를 위하여 반환값을 갖느냐의 차이라고 생각하는데

의사결정을 한다면 
1. 이대로 수정하는 로직으로 사용한다.
2. 수정 후 변경된 유저의 상태를 반환한다.
3. 수정 후 변경된 유저 정보를 반환한다. 
정도가 될 것 같은데 의견 조율하여 결정하면 될 것 같습니다. 의견 부탁드립니다.

2022-04-08 00:43 UTC, DoLiLu commented on module-user/src/main/kotlin/com/example/user/application/port/in/CreateStreamerUserUseCase.kt
> +)
그럼 이 이슈도 일단 보류 후 Infra때 추가 수정하는 방향으로 가는걸까요?

2022-04-08 01:18 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/port/in/UpdateStreamerUserUseCase.kt
>      fun updateStreamerNickname(id: UUID, updateNickname: String)
음, 명확한 의도가 있다면 그렇게 하셔도 될 것 같습니다.

2022-04-08 01:37 UTC, FrancescoJo approved these changes

2022-04-08 01:37 UTC, FrancescoJo commented on module-user/src/main/kotlin/com/example/user/application/service/UpdateStreamerUserService.kt
>      override fun approveStreamerUser(streamerUsers: List<StreamerUser>) {
그렇다기 보다는, 'Service', 'Use Case' 등으로 분리해서 뭔가를 하는것 보다는 Domain Model 안으로 로직을 최대한 밀어넣는 방식(Rich domain model) 이 좀더 일관성 있고 자연스러운 흐름을 만든다는 이야기였습니다. 'Approve' 가 결국 StreamerUser 의 상태를 바꾸는 건데, 남이 StreamerUser 를 바꾸는게 아니라, StreamerUser 가 스스로 상태를 바꾸도록 지시하는 형태로 구현하는 거죠.

2022-04-08 08:38 UTC, Hyune-c approved these changes

2022-04-08 09:10 UTC, merged