Issue 40 JPA 설정 추가
f-lab-edu/twitch-clone pull request #41
Opened 2022-04-27 10:46 UTC by DoLiLu

2022-04-27 10:52 UTC, DoLiLu commented on module-api/build.gradle.kts
일단 queryDsl은 제외한 상태인데, 관련하여 어떻게 진행할지 의견 부탁드립니다.
필요하다고 생각하시면 추가하겠습니다.
저는 필요할 것 같다고 생각하는데, 저번에 멘토님이 없이 해보자고 하셨던거 같아 일단 제외하였습니다.

2022-04-27 10:52 UTC, DoLiLu commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +) : User.Editor by NormalUser(id, email, password, nickname) {
처음에 `NormalUser`를 상속받는 구조로 진행 하였으나, 제대로 엔티티가 생성되지 않아서 `User.Editor`를 구현하는 형태로 진행 하고 `NormalUser`에 위임하는 형태로 진행 했는데, 그냥 `User.Editor` 구현하는 것 밖에 안되는것 같아 원하는 방향이 아니라고 생각됩니다. 
개선 방향 알려주시면 맞춰 수정 진행 하겠습니다.

2022-04-27 10:52 UTC, DoLiLu commented on module-api/src/main/kotlin/com/example/user/adpter/out/NormalUserRepositoryImpl.kt
> +        normalUserDao.save(NormalUserEntity.from(normalUser))
`fun`매개변수인 도메인 모델과, 실제 저장하는 엔티티가 달라 매핑 하는 로직이 필요한데 이런 형태가 맞는지 궁금합니다.
`save`의 경우 한번의 변환이지만 
`select or update`의 경우 `entity -> domain -> entity` 변환이 계속 반복될 것 같아 어떻게 진행하는 것이 맞는지 잘 모르겠습니다.

2022-04-28 00:26 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/adpter/out/NormalUserRepositoryImpl.kt
> +        normalUserDao.save(NormalUserEntity.from(normalUser))
음, 이 문제 때문에 저희회사 sandbox 에는 `editor` 라는 타입을 추가로 둔 거구요,

`NormalUser` 는 외부에 노출할 타입이고, `NormalUserEntity` 는 entity 로 숨길 타입이 될 겁니다.

일단 이 경우는 파라미터로 주입받은 `normalUser` 를 반환하는게 아니라 save 결과를 반환하도록 하는게 좋겠습니다.

또한 `NormalUserEntity` 가 `NormalUser` 의 기능을 모두 구현한다면 문제가 없을 것 같아요.

2022-04-28 00:27 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +) : User.Editor by NormalUser(id, email, password, nickname) {
원래 의도가 이게 맞습니다. 잘 해 주셨어요.

아니라면 차라리 모든 field 들을 var 로 바꿔버리는 것도 방법입니다.

2022-04-28 00:27 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +class NormalUserEntity(
Entity 를 외부에 노출할 이유가 없으니 `internal` 로 바꿔주세요

2022-04-28 00:28 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "CHAR(36)")
UUID 는 16-bytes 데이터 (long + long) 입니다. VARBINARY(16) 로 선언한다면 인덱싱 비용도, 공간도 대폭 줄일 수 있을 것 같아요.

2022-04-28 00:28 UTC, FrancescoJo requested changes
코멘트 참고해 주세요.

2022-04-28 00:29 UTC, FrancescoJo commented on module-api/build.gradle.kts
> +    kotlin("plugin.noarg") version "1.6.10"
이거 JPA 때문에 추가하신 것 같은데... 뭐 이해는 합니다만, 왠만하면 이런거 없이 kotlin/jvm 에서 default constructor 를 만들 수 있는 방법을 써 보는 것도 나쁘지 않을 것 같아요.

일단 Kotlin 과 JPA(*JAVA* Persistent API) 는 궁합이 별로 좋지 않습니다.

2022-04-28 00:39 UTC, DoLiLu commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +) : User.Editor by NormalUser(id, email, password, nickname) {
이렇게 적용하니 `NormalUser Domain Model`의 기능을 사용할 수가 없는데 `interface`에 존재하지 않고 `NormalUser`에 존재하는 도메인 관련 기능들은 `엔티티`에도 똑같이 구현해야 하는 상황인 것 같습니다.
중복 기능들은 어떤식으로 구현해야 하는걸까요?

2022-04-28 00:42 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +) : User.Editor by NormalUser(id, email, password, nickname) {
저는 그래서 그냥 model 을 interface 로 선언하고, 도메인 로직은 domail model 에 다 몰아넣은 뒤

Entity 는 단순히 데이터베이스를 직렬 / 역직렬 하는 용도로만 간단하게 구현하도록 가이드 하고 있습니다.

`val` 로선언한 키워드도 `var` 로 바꿀 수 있다는 점을 이용하면 entity 를 default mutable 로 만드실 수 있어요.

2022-04-28 00:46 UTC, DoLiLu commented on module-api/src/main/kotlin/com/example/user/adpter/out/NormalUserRepositoryImpl.kt
> +        normalUserDao.save(NormalUserEntity.from(normalUser))
`NormalUserRepository` `interface`의 save는 `NormalUser`를 리턴하고 
`NormalUserDao`의 save는 `NormalUserEntity`를 리턴하는데 `save`결과 반환이 가능한가요?

`NormalUserEntity` 가 `NormalUser`의 기능을 모두 구현한다면  이라고 표현하신 부분이 정확히 이해가 안가는데
`NormalUser` 도메인의 기능들을 `NormalUserEntity`에서 다시 구현해야 한다는 말씀이실까요?
현 구조에서는 `NormalUser` 상속이 아닌 `User Interface`구현하는 형태의 `Entity`라서 어떤식으로 진행해야 하는지 명확하게 모르겠습니다..

2022-04-28 00:48 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/adpter/out/NormalUserRepositoryImpl.kt
> +        normalUserDao.save(NormalUserEntity.from(normalUser))
1. `NormalUser` 와 `NormalUserEntity` 가 타입이 같다면 반환하는데 아무 문제가 없죠. Upcast 된 타입을 반환하는 거니까요.

2. 마찬가지로 두개 타입이 호환되도록 구현한다면 반환하는데 아무 문제가 없습니다. 그리고 Entity 가 비즈니스 오브젝트인가요? 지금 구조에서는 Low level object 인것 같은데요.

2022-05-02 20:37 UTC, DoLiLu commented on module-api/build.gradle.kts
> +    kotlin("plugin.noarg") version "1.6.10"
다시 제거하였습니다.

2022-05-02 20:37 UTC, DoLiLu commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +class NormalUserEntity(
변경하였습니다.

2022-05-02 20:37 UTC, DoLiLu commented on module-api/src/test/kotlin/com/example/user/util/TestUserGenerator.kt
> +        NormalUser(
`TestFixture` 적용하여 `user moduled`의 `Generator code` 가져 오는 것 보다 
약간의 중복이 발생하더라도 의존성 최소화 하는 방향이 맞다고 생각하여 같은 코드지만 `api module`에도 추가하였습니다.

2022-05-03 00:05 UTC, FrancescoJo commented on module-api/src/main/kotlin/com/example/user/domain/model/NormalUserEntity.kt
> +            NormalUserEntity(
이 코드에서, 필드 한두개를 실수로 빼 먹더라도 컴파일 오류가 나지 않습니다. 어떻게 한계를 극복할 수 있을까요?

2022-05-03 00:06 UTC, FrancescoJo commented on module-api/src/test/kotlin/com/example/user/util/TestUserGenerator.kt
> +        NormalUser(
저라면 `testImplementation` 으로 user module 의 test 코드를 가져올 것 같아요.

테스트 코드도 코드니까 중복을 줄이는것은 의미있습니다.

2022-05-03 00:06 UTC, FrancescoJo approved these changes
고생하셨습니다

2022-05-03 10:53 UTC, merged