#5 프로젝트 초기화
f-lab-edu/twitch-clone pull request #6
Opened 2022-03-10 16:01 UTC by Hyune-c

#5

- 각자 기능 개발을 시작하기 전 공통으로 사용될 도메인 모델에 대해 초기 세팅했습니다. 
  - 각 도메인별로 추가되어야 할 필드, 메서드가 있다면 말해주세요.
- 코틀린으로 프로젝트를 처음해봅니다. 워스트 케이스가 있다면 지적해주세요.
  - 패키지 구조나 네이밍도 좋은게 있다면 추천 부탁드립니다.
- 이 PR이 머지된 후에는 디폴트 브랜치를 변경하고 protection을 걸겠습니다.
  - [x] protection 완료

![image](https://user-images.githubusercontent.com/55722186/157872466-f4160b73-cd81-49fb-af21-ea53eb3c4d57.png)

2022-03-10 16:05 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +    fun canStreaming(): Boolean = throw IllegalStateException()
현재까지 개발 환경에서는 리스코프 치환 원칙에 따르지 않고 구현 클래스를 생성했습니다.
즉 이 메서드는 `StreamerUser` 에 만들었었습니다.

하지만 이번에 리스코프 치환 원칙을 지키기 위해 회원의 공통 인터페이스로 올렸습니다.
괜찮은 방법인지 리뷰 부탁드립니다.

2022-03-10 19:12 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +    fun canStreaming(): Boolean = throw IllegalStateException()
`hasStreamingAuthority()`로 메서드명 변경

2022-03-11 13:04 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +    fun canStreaming(): Boolean = throw IllegalStateException()
모델링을 변경하였습니다.

2022-03-11 13:07 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
entity 초기 생성시에는 id가 null일 수 있습니다.

2022-03-11 13:07 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +    }
service를 통해 생성시에는 id가 null일 수 없습니다.

---

DDD를 공부는 했지만 개발은 처음해봅니다.
어떻게할까하다가 JPA entity 생성 방식에서 아이디어를 가져왔는데 좀 더 좋은 방식이 있다면 추천 부탁드립니다.

2022-03-11 13:07 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +    }
key generate 동기화 이슈 등에 대한 것은 좀 더 후에 생각합니다.

2022-03-12 01:03 UTC, DoLiLu commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
User가 도메인 모델이라고 생각한다면 id 는 필요 없을 것 같습니다.
차후 UserEntity등 DB에서 사용 할 엔티티를 만들경우 추가하면 될 것 같습니다.

식별자의 경우 따로 userKey or uuid를 생성하거나 email 정보를 식별자로 사용하면 괜찮을 것 같은데 어떻게 생각하시나요?

active의 경우 사용중 / 정지 두 가지 상태만 갖는다면 문제 없을 것 같으나 탈퇴 or 강제 탈퇴 등 추가 상태가 필요 하다면 상태 플래그를 따로 만들어 줘야 할 것 같습니다.

User 생성일, 상태 변경일 관련 프로퍼티 추가가 필요할 것 같습니다.

2022-03-12 01:04 UTC, DoLiLu commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +    }
위에 말씀드린것 처럼 지금은 없어도 될 것 같습니다.

2022-03-12 01:12 UTC, DoLiLu commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/NormalUserTest.kt
> +    fun 일반회원이_스트리밍여부호출을하면_에러발생(id: Long, email: String, nickName: String) {
테스트 케이스를 한글로 하는것과 영문으로 생성 후 @Displayname 붙이는 방법 중 선택해야 할 것 같은데
한글을 더 선호 하시나요? 
클래스 레벨에 @Displayname 사용하는 것처럼 전체를 @Displayname 사용해서 하는 것도 괜찮을 것 같습니다.
두 번 반복 만들어야 해서 불편하다면 가독성이 조금 떨어지는 것 같아 _ 대신에  아래처럼 ``로 감싸서 공백을 사용하는 것도 괜찮을 것 같습니다.

![스크린샷 2022-03-12 오전 10 06 40](https://user-images.githubusercontent.com/25000238/157997266-a0921db5-c912-404d-9d88-59d834d44231.png)

공백 사용 시 말씀하신 명시화와는 별도로 사용될 것 같아 명시화 관련 얘기를 서로 좀 더 해봐야 할 것 같습니다.

2022-03-12 01:16 UTC, DoLiLu commented on src/test/kotlin/com/example/twitchclone/domain/user/service/CreateUserServiceTest.kt
> +    @MethodSource
@MethodSource 관련 궁금한게 하나 있는데, 
@ParameterizedTest
@MethodSource
사용하여 스트리머 회원 생성 하는 로직이 테스트 클래스 2개에 중복되는데
이렇게 사용하시는 이유가 있나요?
생성 로직을 별도 함수로 빼서 사용하면 중복 제거도 가능할 것 같아서 여쭤봅니다.

2022-03-12 01:23 UTC, DoLiLu commented
저희 모듈화는 언제 진행 할지에 대한 고민도 필요한 것 같습니다.

1. 지금 구조로 개발 진행 후 모듈 분할 해야할 타이밍이라고 생각되는 시점에 분리
2. 시작 전에 core 모듈만 먼저 만들어 놓고 개발 진행 후 추가 모듈 생성

제 생각에는 두 가지 방법이 있을 것 같은데, 어떻게 생각하시나요?

2022-03-12 01:33 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/NormalUserTest.kt
> +    fun 일반회원이_스트리밍여부호출을하면_에러발생(id: Long, email: String, nickName: String) {
> 테스트 케이스를 한글로 하는것과 영문으로 생성 후 @DisplayName 붙이는 방법 중 선택해야 할 것 같은데
한글을 더 선호 하시나요?
클래스 레벨에 @DisplayName 사용하는 것처럼 전체를 @DisplayName 사용해서 하는 것도 괜찮을 것 같습니다.

- 네. 저도 테스트를 처음 만들때는 `@DisplayName`을 사용했습니다.
    - 근데 그러다보니 케이스를 적절한 영작하는 과정에서 모호함을 느껴 그냥 한글 메서드명으로 사용하고 있습니다.
- 즉 저는 지금의 방식이 좋다고 생각합니다.

> 두 번 반복 만들어야 해서 불편하다면 가독성이 조금 떨어지는 것 같아 _ 대신에 아래처럼 ``로 감싸서 공백을 사용하는 것도 괜찮을 것 같습니다.

1. ``로 문자열을 감싸는 것에 찬성합니다. 바로 수정하겠습니다.
2. 근데 저는 `_`로 given, when, then을 구분하려는 의도도 있었는데요. 이건 어떻게 하면 좋을까요?
    - 또는 굳이 형식이 필요 없다는 의견이신가요?

2022-03-12 01:38 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
> User가 도메인 모델이라고 생각한다면 id 는 필요 없을 것 같습니다.
차후 UserEntity등 DB에서 사용 할 엔티티를 만들경우 추가하면 될 것 같습니다.

네. 제거하겠습니다.

> 식별자의 경우 따로 userKey or uuid를 생성하거나 email 정보를 식별자로 사용하면 괜찮을 것 같은데 어떻게 생각하시나요?

- DDD 설계를 제대로 해본적이 없어서 여기에는 제 주관이 부족하네요.
    - 하지만 uuid를 식별자로 만들고 또 db id가 존재한다면 이상하다고 생각합니다.
    - 현재의 구조에서는 email을 식별자로 쓰는 것이 좋다고 생각합니다.
- 하지만 추후 업무가 변경되서 email이 식별자 역할을 할 수 없게된다면 어떻게 해야될지 잘 모르겠네요..
- @f-lab-hwan 의견 부탁드립니다.

> active의 경우 사용중 / 정지 두 가지 상태만 갖는다면 문제 없을 것 같으나 탈퇴 or 강제 탈퇴 등 추가 상태가 필요 하다면 상태 플래그를 따로 만들어 줘야 할 것 같습니다.

네. enum을 사용하도록 수정하겠습니다.

> User 생성일, 상태 변경일 관련 프로퍼티 추가가 필요할 것 같습니다.

이건 도메인 레이어에서는 필요하지 않을 것 같아 일부러 추가하지 않았습니다.
UserEntity에는 추가할 것입니다.

2022-03-12 01:39 UTC, DoLiLu commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/NormalUserTest.kt
> +    fun 일반회원이_스트리밍여부호출을하면_에러발생(id: Long, email: String, nickName: String) {
말씀하신대로 공백을 사용 시 가독성은 늘어나겠지만 given, when, then 구분은 따로 되지 않을 것 같긴 해서 말씀 드렸습니다.
tradeoff 라고 보여지기도 하는데 저는 가독성이 더 중요한 것 같습니다.
given, when, then의 경우 테스트 코드를 통해서 사용하기도 하고 꼭 _ 구분이 아니더라도 가독성이 좋으면 
읽으면서 given, when, then 구분을 할 수 있을 것 같아서 문제 없을 것 같습니다.

2022-03-12 01:40 UTC, Hyune-c commented
> 저희 모듈화는 언제 진행 할지에 대한 고민도 필요한 것 같습니다.

전 이 프로젝트를 회사의 레거시 프로젝트 개선과 같은 방향으로 생각하고 있습니다.
따라서 모듈화되지 않은 버전으로 MVP 개발 후, 다음 버전의 MVP로 넘어가는 과정에서 모듈화를 하면 좋을 것 같다고 생각합니다.

2022-03-12 01:42 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/NormalUserTest.kt
> +    fun 일반회원이_스트리밍여부호출을하면_에러발생(id: Long, email: String, nickName: String) {
네. 그러면 아래와 같이 수정하겠습니다.

- 메서드명 한글 유지.
- 메서드명 ``로 감싸고 `_`는 제거.

2022-03-12 01:45 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/domain/user/service/CreateUserServiceTest.kt
> +    @MethodSource
테스트를 위한 더미 데이터 생성 방법에는 어느정도 중복이 있어도 된다고 생각합니다.
향후 테스트가 많아져 일괄적으로 초기 데이터가 필요한 시점이 온다면 그 때 묶어도 된다고 생각합니다.

2022-03-12 01:51 UTC, DoLiLu commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
저는 도메인 레이어에서도 필요 할 것 같아서 말씀 드리긴 했는데, 엔티티는 결국 저장 하기 위하여 생성 하는 부분이라면
도메인 레이어에도 존재해야 하지 않을까요?

uuid를 생성한다면 generate Id 없이 uuid를 pk로 사용해도 괜찮을 것 같습니다.

2022-03-12 02:36 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
이건 좀 모호하네요.. 제가 접근한 방식은 아래와 같습니다.

- JPA 방식으로 서비스에서 entity를 만드는 시점에는 대리키(PK)가 없고 영속 단계에서 생깁니다.

---

도메인 레이어에서도 사용하고 영속성 레이어에서도 사용하기 위해 UUID를 사용하자는 의견에 대해서는 아래와 같습니다.

- 중복 가능성이 이론상 0은 아니다. 
    - 따라서 라이프 사이클이 짧은 세션으로 쓰는 것은 찬성하지만, 영속성이 유지되어야 할 회원의 PK로 쓰기는 꺼림직하다.
- PK 저장 공간이 상대적으로 크다. 
    - 하지만 하드웨어 비용이 저렴한 지금은 큰 문제가 아닐지도?
- 도메인 모델로 가게 되면 UUID이던 db에서 생성되는 PK이던 프론트가 알 필요가 없지 않을까?
    - UUID와 같은 대리키가 아닌 약속된 unique키로 조회하면 된다고 생각합니다.
    - 지금의 방향에서는 email

---

DDD 설계가 처음이라 미숙한데 이건 @f-lab-hwan 의 의견도 받고 싶습니다.

2022-03-12 02:42 UTC, Hyune-c commented
PK genetate 외 리뷰 항목 수정 완료.

2022-03-12 02:46 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/domain/user/service/CreateUserServiceTest.kt
> +    @MethodSource
@f-lab-hwan

2022-03-13 14:24 UTC, FrancescoJo commented on build.gradle.kts
> +dependencies {
여기 spring 의존성은 개별 모듈로 빼 주시는게 좋겠어요

2022-03-13 14:26 UTC, FrancescoJo commented on settings.gradle.kts
> +rootProject.name = "twitch-clone"
multi module 로 분리해주세요.

우선 지금은 core 모듈 하나만 있어도 될것 같으니까 `PROJECT_ROOT/core` 같은 디렉토리를 모듈로 만들어주세요

2022-03-13 14:27 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/TwitchCloneApplication.kt
> +@SpringBootApplication
spring app 추가하실거면, `PROJECT_ROOT/spring-boot` 같은 모듈을 하나 만들고 거기 요녀석을 넣어주세요

2022-03-13 14:27 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/StreamerUser.kt
> +class StreamerUser(
NIT: module 분리

2022-03-13 14:27 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserStatus.kt
> +enum class StreamerUserStatus(val description: String) {
NIT: module 분리

2022-03-13 14:27 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +class User(
NIT: module 분리

2022-03-13 14:28 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/StreamerUser.kt
> +    val user: User, // table 구조에서는 userId만 가지지만 객체 관계로 표현합니다.
table 같은거 지금 단계에서는 몰라도 될것 같습니다

2022-03-13 14:28 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/StreamerUser.kt
> +class StreamerUser(
아마 이 파일은 매우 높은확룰로 abstract class 또는 interface 가 되겠네요

2022-03-13 14:29 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/UserStatus.kt
> +enum class UserStatus(val description: String) {
NIT: module 분리

2022-03-13 14:29 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +class CreateUserService {
NIT: module 분리

2022-03-13 14:30 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +class CreateUserService {
`open` 키워드 없으면 kotlin 은 기본적으로 final class 라서, 이 클래스 사용처에서 테스트 시나리오시 mock을 만들 수 없습니다.
문제 해결하려면 어떻게 하는게 좋을까요?

2022-03-13 14:35 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/TwitchCloneApplicationTests.kt
> +    val logger: Logger = LogManager.getLogger(TwitchCloneApplication::class.java)
service 나 repository 에서 쓰실 때 logger 는 static 참조보다 주입받도록 구현해주세요.

그리고 나중에 bean type = prototype 으로 bean 설정을 추가하는 식으로 해 주시기 바랍니다.

https://stackoverflow.com/questions/2682553/which-pattern-to-use-for-logging-dependency-injection-or-service-locator

Logger 는 무 조건 static 이라는 환상을 이제는 버릴 때입니다. Logger 도 주입의 대상이 되어야 합니다.

https://bradirby.com/logger-injection-vs-static-logging/

2022-03-13 14:36 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +    companion object {
https://kotlinlang.org/docs/coding-conventions.html#class-layout

`companion object` 는 소스코드의 제일 아래쪽으로 옮겨주세요

2022-03-13 14:37 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +    fun `스트리머회원 생성`(user: User, streamingName: String) {
test 이름을 `DisplayName` 을 이용해 하나의 완결된 문장으로 표현해 주세요

`*User 정보를 입력하면, 스트리머 회원이 생성된다*`

처럼요.

2022-03-13 14:39 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +        assertThat(streamer.user.status).isEqualTo(UserStatus.REGISTERED)
muliple assert 는 첫번째 assert 실패시 다음 assert 를 수행 못하는 문제가 있으니까, 

[`assertAll`](https://junit.org/junit5/docs/5.0.0-M2/api/org/junit/jupiter/api/Assertions.html#assertAll) 을 이용해 모두 감싸주는게 좋습니다.

2022-03-13 14:41 UTC, FrancescoJo requested changes

2022-03-13 14:41 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/UserTest.kt
> +    fun `일반회원 생성`(email: String, nickName: String) {
NIT: 테스트 이름을 완결된 한 문장으로

2022-03-13 14:41 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/service/CreateUserServiceTest.kt
> +    @MethodSource
네 맞아요. parameterised test 는 특성상 중복처럼 보이는게 있을 수 있습니다.

2022-03-13 14:41 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/service/CreateUserServiceTest.kt
> +    fun `스트리머회원 생성`(user: User, streamingName: String) {
NIT: test name 을 완결된 한 문장으로 표현

2022-03-13 14:42 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
지금 단계에서 테이블이니 뭐니를 생각할 필요가 없을 것 같아요. 그냥 객체 연결 관계만 표현해주세요.

2022-03-13 14:43 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
나중에 진짜로 저장이 필요한 단계때,

설계를 얼마나 잘했냐 못했냐에 따라 수정이 고통스럽거나 아니면 할만하거나가 보일겁니다.

2022-03-13 14:45 UTC, FrancescoJo commented
저는 그냥 처음부터 모듈로 만들어서 시작하시길 권해드립니다. 왜냐면 처음부터 의존성을 빡빡하게 제어하면서 하는게 오히려 나중에 수정비용이 더 적어서 좋거든요. 

아무 생각없이 써 왔던 `@Service`, `@Component` 없이 어떻게 DI 를 구현할 수 있을지 한번 느껴보시죠.

**객체 생성이 OOP 에서 제일 중요하고 제일 어렵다는 개소리** 가 더이상 개소리처럼 들리지 않을 겁니다.

2022-03-13 15:24 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/NormalUserTest.kt
> +    fun 일반회원이_스트리밍여부호출을하면_에러발생(id: Long, email: String, nickName: String) {
스타일은 두분이 결정하시면 될 것 같아요. 저는 개인적으로는 backtick 으로 감싼 이름과 `@DisplayName` 둘다 씁니다. 왜냐면 backtick 안에는 들어갈 수 있는 글자가 제한되어 있어서 표현력이 그다지 좋진 않거든요.

2022-03-13 17:32 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
네 그렇다면 도메인 레이어에서 PK를 만들지 않는 지금의 구성을 유지하겠습니다.
만약 이것이 잘못된 설계라면 repo 연결과정에서 문제가 될 것이라 그것을 경험하는 것도 좋을 것 같아요.

2022-03-13 17:44 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +        assertThat(streamer.user.status).isEqualTo(UserStatus.REGISTERED)
이건 옛날부터 궁금했던 것인데요.
하나의 assert라도 실패하면, 굳이 다음 테스트를 수행할 필요 없이 빨리 실패로 표기하고 다음으로 넘어가는 것이 좋은 것 아닌가요? (if-else 패턴에서 적용하능한 early return에서 착안함)

- 물론 하나의 단위 테스트에 많은 assert가 들어가는 것 부터가 이상한 설계임으로 분리해야됩니다.
- 이것은 좋은 단위 테스트의 4대 요소 중 하나인 `빠른 피드백`과도 연결된다고 생각합니다.

이런 이유로 저는 assertAll을 사용하지 않습니다.

2022-03-13 20:11 UTC, Hyune-c commented on build.gradle.kts
> +dependencies {
모듈화를 하면서 spring을 사용하지 않는 구성으로 변경했습니다.

2022-03-13 20:12 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/TwitchCloneApplication.kt
> +@SpringBootApplication
모듈화를 하면서 spring을 사용하지 않는 구성으로 변경했습니다.

2022-03-13 20:12 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserStatus.kt
> +enum class StreamerUserStatus(val description: String) {
`module-user` 로 분리했습니다.

2022-03-13 20:12 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +class User(
`module-user` 로 분리했습니다.

2022-03-13 20:13 UTC, Hyune-c commented on src/test/kotlin/com/example/twitchclone/TwitchCloneApplicationTests.kt
> +    val logger: Logger = LogManager.getLogger(TwitchCloneApplication::class.java)
logging 은 core 영역에서 하는 것이 좋다고 생각하여 분리했습니다.
하지만 어떻게 테스트해야될지는 잘 모르겠어서 세팅만 해놨습니다.

2022-03-13 20:21 UTC, Hyune-c reviewed
- 이왕 새로 해보는거 Groovy DSL이 아닌 Kotlin DSL로 해보려고 합니다.
    - lib 버전은 spring boot 2.6.4 dependency를 참고합니다.
- `module_user` `module_core` `module_api` 로 만들 예정.
    - api에 spring boot를 연결할 생각입니다.

---

@FrancescoJo 
근데 이렇게 모듈별로 dependency 세팅을 하다보니 느낀건데요.
그러면 spring과 관련없는 모듈에서는 spring boot starter를 사용할 수 없어 일일히 찾아서 설정을 해줘야됩니다.
spring boot의 강력한 기능 중 하나가 편리한 버전 관리로 알고 있는데, 그것을 포기하는 것이 더 좋은건가요?

2022-03-13 20:21 UTC, Hyune-c commented on module-user/build.gradle.kts
> +    testImplementation("org.assertj:assertj-core:3.21.0")
이왕 해보는거 `Groovy DSL`이 아닌 `Kotlin DSL`로 해보려고 합니다.
근데 이것저것 해봤는데 잘 안되더라구요..
좀 더 공부하고 수정하겠습니다.

2022-03-14 05:26 UTC, FrancescoJo commented
> * 이왕 새로 해보는거 Groovy DSL이 아닌 Kotlin DSL로 해보려고 합니다.
>   
>   * lib 버전은 spring boot 2.6.4 dependency를 참고합니다.
> * `module_user` `module_core` `module_api` 로 만들 예정.
>   
>   * api에 spring boot를 연결할 생각입니다.
> 
> @FrancescoJo 근데 이렇게 모듈별로 dependency 세팅을 하다보니 느낀건데요. 그러면 spring과 관련없는 모듈에서는 spring boot starter를 사용할 수 없어 일일히 찾아서 설정을 해줘야됩니다. spring boot의 강력한 기능 중 하나인 `편리한 버전 관리`를 포기하는 것이 더 좋은가요?

특정 module 안에다가 build plugin 부터 적어주면 버전 안 적어줘도 여전히 같은 기능 쓸 수 있을걸요?
그리고 sirloin sandbox 보시면 버전을 아예 상수로 빼 놓은 스크립트를 확인하실 수 있습니다.

2022-03-14 05:27 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +        assertThat(streamer.user.status).isEqualTo(UserStatus.REGISTERED)
그건 fail-first approach 랑은 조금 다른것 같아요.

최악의 경우 한개 고치고 또 다음꺼 고치고... 순으로 갈 수도 있지 않나요?
내가 만든 테스트코드는 assert 여러개 하더라도, 단 한개만 깨진다고 항상 말씀하실 수 있나요?

2022-03-14 05:27 UTC, FrancescoJo commented on src/test/kotlin/com/example/twitchclone/domain/user/entity/StreamerUserTest.kt
> +        assertThat(streamer.user.status).isEqualTo(UserStatus.REGISTERED)
물론 assert 를 여러번 하는것 자체가 이미 문제지만 그런 경우가 있을때는 `assertAll` 로 전체를 감싸주는게 낫다고 봅니다.

2022-03-14 05:32 UTC, FrancescoJo commented on src/main/kotlin/com/example/twitchclone/domain/user/entity/User.kt
> +)
뭔가 객체를 검색하기 위한 식별자(또는 hash) 같은게 필요할 수는 있는데 그게 꼭 DB 의 PK FK 와 일치할 필요는 없습니다

2022-03-14 17:23 UTC, Hyune-c commented on module-user/src/test/kotlin/com.example.domain.user/entity/StreamerUserTest.kt
> +        )
```suggestion
        // then
        assertThat(streamer.user.status).isEqualTo(UserStatus.REGISTERED)
        assertThat(streamer.status).isEqualTo(StreamerUserStatus.PENDING)
```

코멘트를 수용하여 assertAll을 추가했습니다.
하지만 이게 묶기 전보다 가독성이 좋거나 보일러 플레이트가 적은가? 에 대해서는 여전히 의문이 있습니다.

좀 더 내용을 찾아보니 이렇게 보일러 플레이트가 생기는 이유는 `람다가 자동 캐스팅되지 않는 현재 코틀린의 한계`라고 합니다.

```
At present, there’s no support for automatically casting a lambda to a functional interface, so we need to do it by hand
```

[Multiple Assertions - baeldung](https://www.baeldung.com/kotlin/junit-5-kotlin#2-multiple-assertions)

2022-03-14 23:47 UTC, FrancescoJo commented on module-user/src/test/kotlin/com.example.domain.user/entity/StreamerUserTest.kt
> +        )
https://github.com/sirloin-dev/meatplatform-sandbox/blob/main/server/api-core/src/test/kotlin/testcase/small/domain/user/UserSpec.kt

이거 한번 보세요. 이정도면 꽤 읽을만 하지 않나요?

2022-03-14 23:48 UTC, FrancescoJo commented on module-user/build.gradle.kts
> +    testImplementation("org.assertj:assertj-core:3.21.0")
좋습니다

2022-03-14 23:50 UTC, FrancescoJo approved these changes
Test 쪽 수정 후 병합해주세요. Test code 의 퀄리티에 특히 신경써 주시는게 좋습니다.

구현은 왠만큼 남들도 다 하니까, 구현 잘합니다~~ 이걸론 경력직은 어필하기가 쉽지 않아요.

저는 읽기좋고 유지보수 하기 좋은 테스트를 만드는 능력이 있다
저는 아키텍쳐의 어려움을 테스트라는 도구를 이용해 해결한다

같은걸로 어필하는게 좋다 생각해주세요

2022-03-14 23:57 UTC, FrancescoJo commented
Parameterised test 나 test fixture 이름은 alphanumeric 으로 지어주시고, `@DisplayName` 을 활용해주세요.

저도 한국인인 입장에서 메소드명 backtick 으로 감싸고 한글로 적는게 더 편하긴 한데...
특정 개발도구 / 환경의 경우 alphanumeric 외의 메소드명을 인식하지 못하는 경우가 있어서 그렇습니다.

https://github.com/sirloin-dev/meatplatform-sandbox/blob/main/server/api-core/src/test/kotlin/testcase/small/i18n/DefaultMessageProviderSpec.kt

요거 참고해서 보고 수정해주세요

2022-03-15 00:43 UTC, DoLiLu approved these changes

2022-03-15 00:59 UTC, Hyune-c commented on module-user/src/test/kotlin/com.example.domain.user/entity/StreamerUserTest.kt
> +        )
어? `Executable` 안써도 되네요?
갑자기 깔끔해 보입니다. 이렇게 수정하겠습니다.

2022-03-15 01:23 UTC, Hyune-c commented on src/main/kotlin/com/example/twitchclone/domain/user/service/CreateUserService.kt
> +class CreateUserService {
1. 그냥 시원하게 open class 로 선언
2. https://github.com/sirloin-dev/meatplatform-sandbox/blob/main/server/api-core/src/main/kotlin/com/sirloin/sandbox/server/core/domain/user/service/CreateUserService.kt 여기 예제처럼 구체타입을 숨기면서, interface 만 노출

2022-03-15 03:16 UTC, merged